### ISSUE TITLE
Не могу установить nextcord

### ISSUE THREAD

**Issue by bezvozni** [TVP-Support/TVP-discord-bot#30]
При выполнении команды 

pip install nextcord

получаю ошибку:

ERROR: Could not find a version that satisfies the requirement nextcord (from versions: none)
ERROR: No matching distribution found for nextcord

Вероятно нужно обновить python с 3.7.8 до 3.8

**Comment by redboo** [comment]
Где ты здесь увидел, что нужно сменить питона?
![image](https://user-images.githubusercontent.com/16482188/154858166-21cc3f58-e646-4ec2-bdd4-60e722f984ea.png)

**Comment by bezvozni** [comment]
версию я указывал, дело не в этом
обновление питона помогло
nextcord требует не менее 3.8
