### ISSUE TITLE
Не удаляются голосовые каналы

### ISSUE THREAD

**Issue by redboo** [TVP-Support/TVP-discord-bot#4]
При перезагрузке бота, созданные до этого момента, активные голосовые каналы не удаляются после выхода последнего пользователя.

**Comment by bezvozni** [comment]
Причина: бот хранит некоторые данные в своих переменных, из-за чего при перезапуске всё забывает.
Хорошо бы вообще перейти на облачную базу данных (такую как firebase, например) и хранить данные уже там
